### ISSUE TITLE
Remove ed25519-dalek as it's fixed

### ISSUE THREAD

**Issue by hazae41** [MystenLabs/ed25519-unsafe-libs#19]
Hey, according to this issue https://github.com/dalek-cryptography/ed25519-dalek/issues/298, the unsafe signature problem is now fixed, so ed25519-dalek can be removed from the list

**Comment by kchalkias** [comment]
Thanks @hazae41 
Updated here: https://github.com/MystenLabs/ed25519-unsafe-libs/pull/20
